config/routes.rb
Historacle::Application.routes.draw do

  resources :areas

  get 'application/here'

  match "/explorer" => "explorer#index"
  get "explorer/index"
  get "explorer/index1"
  get "explorer/index2"
  get "explorer/index3"
  get "explorer/timeline"

  get "homebase/index"

  resource :libraries, only: [:edit, :show, :update], path: 'library', as: 'library'

  resources :chronicles, only: [:create, :new, :edit, :show, :update, :destroy] do
    resources :events do
      collection { post :import }
      end
    resources :areas
  end

  devise_for :users

  root :to => "homebase#index"

end

app/models/library.rb
class Library < ActiveRecord::Base
  attr_accessible :name, :user_id, :chronicles_attributes
  has_many :chronicles, :dependent => :destroy
  belongs_to :user
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  before_filter :authenticate_user!

  # GET /libraries
  # GET /libraries.json
  def index
    @libraries = Library.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @libraries }
    end
  end

  # GET /libraries/1
  # GET /libraries/1.json
  def show

    @library = current_user.library || Library.create(user_id: current_user.id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @library }
    end
  end

  # GET /libraries/new
  # GET /libraries/new.json
  def new
    @library = Library.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @library }
    end
  end

  # GET /libraries/1/edit
  def edit
    @library = current_user.library || Library.create(user_id: current_user.id)
  end

  # POST /libraries
  # POST /libraries.json
  def create
    @library = Library.new(params[:library])

    respond_to do |format|
      if @library.save
        format.html { redirect_to @library, notice: 'Library was successfully created.' }
        format.json { render json: @library, status: :created, location: @library }
      else
        format.html { render action: "new" }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /libraries/1
  # PUT /libraries/1.json
  def update
    @library = current_user.library || Library.create(user_id: current_user.id)

    respond_to do |format|
      if @library.update_attributes(params[:library])
        format.html { redirect_to library_path, notice: 'Library was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libraries/1
  # DELETE /libraries/1.json
  def destroy
    @library = Library.find(params[:id])
    @library.destroy

    respond_to do |format|
      format.html { redirect_to libraries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/libraries/_form.html.erb
<%= simple_form_for(@library, url: '/library', method: :PUT, :html => {:class => 'form-horizontal'}) do |f| %>

    <%= f.input :name %>

    <div class="control-group">
      <div class="controls">
        <div class="actions">
          <%= f.submit class: "btn" %>
        </div>
      </div>
    </div>

<% end %>

app/views/libraries/edit.html.erb
<h1>Editing library</h1>

<%= render 'libraries/form' %>

<%= link_to 'Show', :root %> |
<%= link_to 'Back', :root %>

app/views/libraries/new.html.erb
<h2>New library</h2>
<br/>

<%= render 'form' %>

<%= link_to 'Back', libraries_path %>

app/views/libraries/show.html.erb
<div class="row">
  <div class="span12">
    <div class="library-wrapper">
      <div class="library-wrapper-inner">
        <div class="library-panel">
          <div class="title wallpaper">
            <h2><%= @library.name || "My Library" %></h2>
          </div>

          <div class="details">
           <%= link_to 'Edit', edit_library_path %>  |
           <%= link_to 'New Chronicle', new_chronicle_path %>
          </div>
          <div class="border" style="padding: 0 5px;">
            <%= render 'chronicles/index_by_library' %>
          </div>


          <div class="footer wallpaper"></div>
        </div>
      </div>
    </div>
  </div>
</div>

<style type="text/css">

   .library-panel {
      height: 100%;
      position: relative;
      border-radius: 8px;
      font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
   }

   .library-panel div.details {
      padding: 10px;
      color: white;
      background-color: rgba(6, 6, 6, 0.75);
   }

   .library-panel div.sub-title {
      padding: 10px;
      min-height: 18px;
      border-top: 1px solid #000;
   }

   .library-panel div.title h2 {
      padding: 15px;
      margin-bottom: 0;
   }

   .library-panel div.title {
      margin-top: 0px;
      border-radius: 8px 8px 0 0;
      text-align: center;
      border-bottom: 1px solid #000;
   }

   .library-panel .control-bar {
      background: url(/images/bg-wrapper.jpg);
   }

   .library-wrapper h4{
      font-weight: 200px;
   }

   .library-wrapper {
      border-radius: 8px;
      -webkit-box-shadow: 3px 0px 15px -2px rgb(0, 0, 0);
   }

   .library-wrapper-inner {
      position: relative;
      border-radius: 8px;
      background: white;
   //padding: 3px 3px 3px 4px;
   //-webkit-box-shadow: inset 0px 0px 10px rgba(0, 0, 0, 0.55);
   //-moz-box-shadow: inset 0px 0px 10px rgba(0, 0, 0, 0.55);
   //box-shadow: inset 0px 0px 10px rgba(0, 0, 0, 0.55);
   }

   .library-wrapper .footer {
      left: 0;
      right: 0;
      bottom: 0;
      position: absolute;
      min-height: 30px;
      border-radius: 0 0 8px 8px;
   }

   .library-panel table {
      padding: 0 10px 10px 10px;
   }

   .library-panel table tr:nth-child(2n) {
      background: url(/images/bg-wrapper.jpg);
   }

   .library-panel table tr:nth-child(odd) th,
   .library-panel table tr:nth-child(odd) td {
      background-color: transparent;
   //background: url(/images/bg-wrapper2.jpg);
   }

   .library-panel table a {
      color: #878787;
      cursor: hand;
      cursor: pointer;
   }

   .library-panel table a:hover {
      color: #787878;
      text-decoration: none;
   }

</style>