config/routes.rb
Historacle::Application.routes.draw do

  resources :areas

  get 'application/here'

  match "/explorer" => "explorer#index"
  get "explorer/index"
  get "explorer/index1"
  get "explorer/index2"
  get "explorer/index3"
  get "explorer/timeline"

  get "homebase/index"

  resource :libraries, only: [:edit, :show, :update], path: 'library', as: 'library'

  resources :chronicles, only: [:create, :new, :edit, :show, :update, :destroy] do
    resources :events do
      collection { post :import }
      end
    resources :areas
  end

  devise_for :users

  root :to => "homebase#index"

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :title, :chronicle_id, :start_date, :end_date, :description, :latitude, :location, :longitude, :image_url
  validates_presence_of :title, :latitude, :longitude
  belongs_to :chronicle

  serialize :properties, Hash
  geocoded_by :location

  validate :validate_properties

  def validate_properties
    chronicle.fields.each do |field|
      if field.required? && properties[field.name].blank?
        errors.add field.name, "must not be blank!  "
      end
    end
  end

  def self.import(file, chronicle)
    CSV.foreach(file.path, headers: true) do |row|
      event = find_by_id(row["id"]) || chronicle.events.build
      event.attributes = row.to_hash.slice(*accessible_attributes)
      event.save!
    end
  end

  def print_dates
    date_string = self.end_date ? " - " + self.end_date.strftime("%b %e %Y") : ""
    self.start_date.strftime("%b %e %Y") + date_string
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!

  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    @chronicle = @event.chronicle
    @events = @chronicle.events.order(sort_column2 + " " + sort_direction2).paginate(:per_page =>10, :page => params[:page])

    respond_to do |format|
      format.html # show.html.erb
      format.js { render :show }
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @chronicle = Chronicle.find(params[:chronicle_id])
    @event = @chronicle.events.build

    respond_to do |format|
      format.js { render :new }
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @chronicle = Chronicle.find(params[:chronicle_id])
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @chronicle = Chronicle.find(params[:chronicle_id])
    @events = @chronicle.events.order(sort_column2 + " " + sort_direction2).paginate(:per_page =>10, :page => params[:page])
    @event = @chronicle.events.build(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @chronicle, notice: 'Event was successfully created.' }
        format.js { render :show, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @chronicle = Chronicle.find(params[:chronicle_id])
    @events = @chronicle.events.order(sort_column2 + " " + sort_direction2).paginate(:per_page =>10, :page => params[:page])
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @chronicle, notice: 'Event was successfully updated.' }
        format.js { render :show, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @chronicle = Chronicle.find(params[:chronicle_id])
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to @chronicle, notice: 'Event was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def import
    @chronicle = Chronicle.find(params[:chronicle_id])
    Event.import(params[:file], @chronicle)
    redirect_to @chronicle, notice: "Events Imported"
  end

  #Railscasts 228
  helper_method :sort_column, :sort_direction
  private

  def sort_column
    (Chronicle.column_names.include?(params[:sort])) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def sort_column2
    (Event.column_names.include?(params[:sort])) ? params[:sort] : "title"
  end

  def sort_direction2
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/helpers/events_helper.rb
module EventsHelper

end

app/views/events/_edit.html.erb
<%= render 'form' %>

app/views/events/_event.html.erb
<fieldset>
  <p class="event-date"><%= event.start_date.strftime("%B %d, %Y") %></p>
  <p class="event-location"><%= event.location %></p>
  <p class="event-title"><%= event.title %></p>

  <% if event.image_url %>
     <img src="<%= event.image_url %>" alt="">
  <% end %>

  <p class="event-description"><%= event.description %></p>

  <% event.properties.each do |name, value| %>
     <% unless value.to_s == "" %>
        <div><b><%= name %></b></div>
        <div class="inline-help"><%= value %></div>
     <% end %>
  <% end %>

</fieldset>

app/views/events/_form.html.erb
<%= simple_form_for([@chronicle, @event], html: {class: 'form-horizontal'}, remote: true) do |f| %>

   <%= f.error_notification %>
   <div class="control-group string" style="margin: 10px 10px 10px 0;">
     <label class="control-label"></label>
     <div class="controls">
       <h3>Event Editor</h3>
     </div>
   </div>

   <div class="title"><%= f.input :title %></div>

   <%= f.input :start_date, start_year: Date.current.year - 250, end_year: Date.current.year + 1, :include_blank => true %>
   <%= f.input :end_date, start_year: Date.current.year - 250, end_year: Date.current.year + 1, :include_blank => true %>

   <div class="control-group string">
     <label class="control-label">Locator</label>

     <div class="controls">
       <div class="input-append">
         <input class="string geocode-input span2" id="appendedInputButton" type="text">
         <button class="btn submit-geocode" type="button"><i class="icon-search"></i></button>
       </div>

       <div class="event-map">
          <span>
            <%= map_image latitude: @event.latitude, longitude: @event.longitude %>
          </span>
       </div>
     </div>
   </div>


   <div class="control-group string">
     <label class="control-label">Latitude/Longitude</label>

     <style type="text/css">
        .lat-lon-fields input {
           width: 94px;
        }
     </style>

     <div class="controls lat-lon-fields">
       <%= f.number_field :latitude, in: -90...90 %>
       <%= f.number_field :longitude, in: -180...180 %>
     </div>
   </div>
   <%= f.input :location, label: "Location Display" %>
   <%= f.input :description, input_html: {rows: 3} %>
   <%= f.input :image_url %>

   <%= f.fields_for :properties, OpenStruct.new(@event.properties) do |builder| %>
      <% @event.chronicle.fields.each do |field| %>
         <%= render "chronicles/fields/#{field.field_type}", field: field, f: builder %>
      <% end %>
   <% end %>

   <div class="control-group string">
     <label class="control-label"></label>

     <div class="controls"><%= f.submit class: "btn" %></div>
   </div>


<% end %>

app/views/events/_index_by_chronicle.html.erb
<div class="sub-title wallpaper">

  <%= link_to '<i class="icon-plus"></i>'.html_safe, new_chronicle_event_path(@chronicle), remote: true %>  |
  <%= link_to '<i class="icon-upload"></i>'.html_safe, '#' %>

  <div class="pull-right">
    <%= will_paginate @events, next_label: '<i class="icon-arrow-right"></i>', previous_label: '<i class="icon-arrow-left" ></i>' %>
  </div>
</div>

<table id="index-chronicle-events" class="table table-index table-striped table-hover">
  <tr>
    <th class="date"><%= sortable "start_date", "Date" %></th>
    <th class="title"><%= sortable "title", "Event" %></th>
    <th class="action"></th>
  </tr>

  <% @events.each do |event| %>
     <tr data-link="<%= chronicle_event_path(@chronicle, event) %>">
       <td><%= event.start_date.strftime('%Y %b %d') if event.start_date %></td>
       <td><%= event.title %></td>
       <td><%= link_to '<i class="icon-remove"></i>'.html_safe, chronicle_event_path(@chronicle, event), method: :delete, data: {confirm: 'Are you sure?'} %></td>
     </tr>
  <% end %>
</table>

app/views/events/_new.html.erb
<%= render 'form' %>

app/views/events/_show.html.erb
<div class="event-view pull-center">
  <h3><%= @event.title %></h3>

  <div class="title "><%= @event.print_dates %></div>

  <% if @event.image_url %>
     <div class="pull-center">
       <b class="curl">
         <b>
           <img src="<%= @event.image_url %>" alt="">
         </b>
       </b>
     </div>
  <% end %>

  <p>
    <b>Description:</b>
    <%= @event.description %>
  </p>

  <% @event.properties.each do |name, value| %>
     <% unless value.to_s == "" %>
        <div><b><%= name %></b></div>
        <div class="inline-help"><%= value %></div>
     <% end %>
  <% end %>

  <%= link_to "Edit", edit_chronicle_event_path(@event.chronicle, @event), remote: true %>


</div>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/edit.js.erb
$("#featured-event").html("<%= j render("edit") %>");

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Date</th>
    <th>Location</th>
    <th>Longitude</th>
    <th>Latitude</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.title %></td>
    <td><%= event.start_date %></td>
    <td><%= event.location %></td>
    <td><%= event.longitude %></td>
    <td><%= event.latitude %></td>
    <td><%= event.description %></td>
    <td><%= link_to 'Show', library_chronicle_event_path(event) %></td>
    <td><%= link_to 'Edit', edit_library_chronicle_path(event) %></td>
    <td><%= link_to 'Destroy', library_chronicle_event_path(event), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_library_chronicle_event_path(@chronicle)%>

app/views/events/new.html.erb
<%= render 'new' %>

app/views/events/new.js.erb
$("#featured-event").html("<%= j render("events/new") %>");

app/views/events/show.html.erb
<div class="pricing-table">
  <div class="color-666777">
    <h3>@event.title</h3>

    <div class="title"><%= @event.start_date + " - " + @event.end_date %></div>

    <p>
      <b>Latitude:</b>
      <%= @event.latitude %>
    </p>

    <p>
      <b>Longitude:</b>
      <%= @event.longitude %>
    </p>

    <p>
      <b>Map:</b>
      <%= map_image latitude: @event.latitude, longitude: @event.longitude %>
    </p>

    <p>
      <b>Description:</b>
      <%= @event.description %>
    </p>

    <%= f.fields_for :properties, OpenStruct.new(@event.properties) do |builder| %>
       <% @event.chronicle.fields.each do |field| %>
          <%= render "chronicles/fields/#{field.field_type}", field: field, f: builder %>
       <% end %>
    <% end %>

  </div>
</div>

app/views/events/show.js.erb
$("#featured-event").html("<%= j render 'show' %>");
$("#events-index-pane").html("<%= j render 'events/index_by_chronicle' %>");