config/routes.rb
Historacle::Application.routes.draw do

  resources :areas

  get 'application/here'

  match "/explorer" => "explorer#index"
  get "explorer/index"
  get "explorer/index1"
  get "explorer/index2"
  get "explorer/index3"
  get "explorer/timeline"

  get "homebase/index"

  resource :libraries, only: [:edit, :show, :update], path: 'library', as: 'library'

  resources :chronicles, only: [:create, :new, :edit, :show, :update, :destroy] do
    resources :events do
      collection { post :import }
      end
    resources :areas
  end

  devise_for :users

  root :to => "homebase#index"

end

app/models/area.rb
class Area < ActiveRecord::Base
  attr_accessible :name, :coordinates, :start_date, :end_date
  validates_presence_of :name

  #belongs_to :chronicle

end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @areas }
    end
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
    @area = Area.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @area }
    end
  end

  # GET /areas/new
  # GET /areas/new.json
  def new
    @area = Area.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @area }
    end
  end

  # GET /areas/1/edit
  def edit
    @area = Area.find(params[:id])
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(params[:area])

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render json: @area, status: :created, location: @area }
      else
        format.html { render action: "new" }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /areas/1
  # PUT /areas/1.json
  def update
    @area = Area.find(params[:id])

    respond_to do |format|
      if @area.update_attributes(params[:area])
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area = Area.find(params[:id])
    @area.destroy

    respond_to do |format|
      format.html { redirect_to areas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/_form.html.erb
<%= form_for(@area) do |f| %>
  <% if @area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
      <% @area.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.datetime_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :coordinates %><br />
    <%= f.text_area :coordinates %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/areas/_index_by_chronicle.html.erb
<div class="sub-title wallpaper">

  <%= link_to '<i class="icon-plus"></i>'.html_safe, edit_chronicle_path(@chronicle) %>  |
  <%= link_to '<i class="icon-upload"></i>'.html_safe, edit_chronicle_path(@chronicle) %>

  <div class="pull-right">
    <%= will_paginate @areas, next_label: '<i class="icon-arrow-right"></i>', previous_label: '<i class="icon-arrow-left" ></i>' %>
  </div>
</div>

<table id="index-chronicle-areas" class="table table-index table-striped table-hover">
  <tr>
    <th class="date"><%= sortable "start_date", "Date" %></th>
    <th class="title"><%= sortable "title", "Event" %></th>
    <th class="action"></th>
  </tr>

  <% @areas.each do |area| %>
     <tr data-link="<%= chronicle_area_path(@chronicle, area) %>">
       <td><%= area.start_date.strftime('%Y %b %d ') %></td>
       <td><%= area.title %></td>
       <td><%= link_to '<i class="icon-remove"></i>'.html_safe, chronicle_area_path(@chronicle, area), method: :delete, data: {confirm: 'Are you sure?'} %></td>
     </tr>
  <% end %>
</table>

app/views/areas/edit.html.erb
<h1>Editing area</h1>

<%= render 'form' %>

<%= link_to 'Show', @area %> |
<%= link_to 'Back', areas_path %>

app/views/areas/index.html.erb
<h1>Listing areas</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Start date</th>
    <th>End date</th>
    <th>Coordinates</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @areas.each do |area| %>
  <tr>
    <td><%= area.name %></td>
    <td><%= area.start_date %></td>
    <td><%= area.end_date %></td>
    <td><%= area.coordinates %></td>
    <td><%= link_to 'Show', area %></td>
    <td><%= link_to 'Edit', edit_area_path(area) %></td>
    <td><%= link_to 'Destroy', area, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Area', new_area_path %>

app/views/areas/new.html.erb
<h1>New area</h1>

<%= render 'form' %>

<%= link_to 'Back', areas_path %>

app/views/areas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @area.name %>
</p>

<p>
  <b>Start date:</b>
  <%= @area.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @area.end_date %>
</p>

<p>
  <b>Coordinates:</b>
  <%= @area.coordinates %>
</p>


<%= link_to 'Edit', edit_area_path(@area) %> |
<%= link_to 'Back', areas_path %>