config/routes.rb
Historacle::Application.routes.draw do

  resources :areas

  get 'application/here'

  match "/explorer" => "explorer#index"
  get "explorer/index"
  get "explorer/index1"
  get "explorer/index2"
  get "explorer/index3"
  get "explorer/timeline"

  get "homebase/index"

  resource :libraries, only: [:edit, :show, :update], path: 'library', as: 'library'

  resources :chronicles, only: [:create, :new, :edit, :show, :update, :destroy] do
    resources :events do
      collection { post :import }
      end
    resources :areas
  end

  devise_for :users

  root :to => "homebase#index"

end

app/models/chronicle.rb
class Chronicle < ActiveRecord::Base
  attr_accessible :description, :name, :subject, :fields_attributes
  has_many :events, :dependent => :destroy
  #has_many :areas, :dependent => :destroy
  has_many :fields, class_name: "ChronicleField"
  accepts_nested_attributes_for :fields, allow_destroy: true
  belongs_to :library

  def self.search(search)
    search ? where('name LIKE ?', "%#{search}%") : scoped
  end

  def first_date
    e = self.events.order("start_date asc").first
    e ? e.start_date : nil
  end

  def last_date
    e = self.events.order("end_date desc").first
    e ? e.end_date : nil
  end
end

app/controllers/chronicles_controller.rb
class ChroniclesController < ApplicationController
  before_filter :authenticate_user!

  # GET /chronicles
  # GET /chronicles.json
  def index
    @chronicles = current_user.library.chronicles.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 10, :page => params[:page])

    #respond_to do |format|
    #  format.html # index.html.erb
    #  format.json { render json: @chronicles }
    #end
  end

  # GET /chronicles/1
  # GET /chronicles/1.json
  def show
    @chronicle = Chronicle.find(params[:id])
    @events = @chronicle.events.order(sort_column2 + " " + sort_direction2).paginate(:per_page =>10, :page => params[:page])
    @event = Event.new(chronicle_id: @chronicle.id)
    respond_to do |format|
      format.html # show.html.erb
      format.js
      format.json { render json: @chronicle }
    end
  end

  # GET /chronicles/new
  # GET /chronicles/new.json
  def new
    @library = current_user.library
    @chronicle = @library.chronicles.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @chronicle }
    end
  end

  # GET /chronicles/1/edit
  def edit
    @library = current_user.library
    @chronicle = Chronicle.find(params[:id])
  end

  # POST /chronicles
  # POST /chronicles.json
  def create
    @library = current_user.library
    @chronicle = @library.chronicles.build(params[:chronicle])

    respond_to do |format|
      if @chronicle.save
        format.html { redirect_to @chronicle, notice: 'Chronicle was successfully created.' }
        format.json { render json: @chronicle, status: :created, location: @chronicle }
      else
        format.html { render action: "new" }
        format.json { render json: @chronicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /chronicles/1
  # PUT /chronicles/1.json
  def update
    @chronicle = Chronicle.find(params[:id])

    respond_to do |format|
      if @chronicle.update_attributes(params[:chronicle])
        format.html { redirect_to @chronicle, notice: 'Chronicle was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @chronicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chronicles/1
  # DELETE /chronicles/1.json
  def destroy
    @chronicle = Chronicle.find(params[:id])
    @chronicle.destroy

    respond_to do |format|
      format.html { redirect_to library_path }
      format.json { head :no_content }
    end
  end

  #Railscasts 228
  helper_method :sort_column, :sort_direction
  private

  def sort_column
    (Chronicle.column_names.include?(params[:sort])) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def sort_column2
    (Event.column_names.include?(params[:sort])) ? params[:sort] : "title"
  end

  def sort_direction2
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/helpers/chronicles_helper.rb
module ChroniclesHelper
  def get_chronicle_date(chronicle)
    first = chronicle.first_date
    last = chronicle.last_date
    _first = (first ? first.strftime("%Y") : "")
    _last = (last ? last.strftime("%Y") : "")
    "#{_first} - #{_last}"
  end

end

app/views/chronicles/_field_fields.html.erb
<fieldset>
  <div class="control-group">
    <div class="controls">
      <%= f.select :field_type, %w[text_field check_box] %>
      <%= f.text_field :name, placeholder: "Field Name" %>
      <%= f.check_box :required %> <br>
      <%= f.label :required, class:"help-inline" %>
      <%= f.hidden_field :_destroy, class: "pull-right" %>
      <%= link_to "[remove]", '#', class: "remove_fields" %>
    </div>
  </div>

</fieldset>

app/views/chronicles/_form.html.erb
<%= simple_form_for(@chronicle,:html => {:class => 'form-horizontal'}) do |f| %>

   <%= f.input :name %>
   <%= f.input :description, :input_html => {:rows => 3} %>
   <%= f.input :subject %>

   <%= f.fields_for :fields do |builder| %>
      <%= render 'field_fields', f: builder %>
   <% end %>
   <%= link_to_add_fields "Add Field", f, :fields %>

   <div class="control-group">
     <div class="controls">
       <div class="actions">
         <%= f.submit class: "btn" %>
       </div>
     </div>
   </div>


<% end %>

app/views/chronicles/_index.html.erb
<table id="index-library-chronicles" class="table table-index ">
  <% @chronicles.each do |chronicle| %>
     <tr>
       <td><%= chronicle.name %></td>
       <td style="width: 24px;"><%= link_to "", "", class: 'icon-plus-sign', :'ng-click' => "getChronicle(\"#{chronicle_path(chronicle)}\")" %></td>
     </tr>
  <% end %>
</table>

app/views/chronicles/_index_by_library.html.erb
<table id="index-library-chronicles" class="table table-index table-striped table-hover">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Tags</th>
    <th></th>
    <th></th>
  </tr>

  <% @library.chronicles.each do |chronicle| %>
     <tr data-link="<%= chronicle_path(chronicle) %>">
       <td><%= chronicle.name %></td>
       <td><%= chronicle.description %></td>
       <td><%= chronicle.subject %></td>
       <td><%= link_to 'Edit', edit_chronicle_path(chronicle) %></td>
       <td><%= link_to 'Destroy', chronicle_path(chronicle), method: :delete, data: {confirm: 'Are you sure?'} %></td>
     </tr>
  <% end %>
</table>

<%= link_to 'New Chronicle', new_chronicle_path %>

app/views/chronicles/_index_for_viewer.html.erb
<table id="index-library-chronicles" class="table table-index ">
  <% @chronicles.each do |chronicle| %>
     <tr>
       <td><%= chronicle.name %></td>
       <td><%= link_to "Add", "", class: 'btn btn-mini pull-right', :'ng-click' => "getChronicle(\"#{chronicle_path(chronicle)}\")" %></td>
     </tr>
  <% end %>
</table>

app/views/chronicles/_show.html.erb
<div class="title">
  <h3><%= @chronicle.name %></h3>
  <div class="pull-right"><%= link_to '<i class="icon-edit"></i>'.html_safe, edit_chronicle_path(@chronicle) %></div>

</div>

<div class="details">
  <p>
    Description: <%= @chronicle.description %>
  </p>

  <p>
    Subject: <%= @chronicle.subject %>          </br>
  </p>

  <%= link_to "Edit", edit_chronicle_path(@chronicle) %>
  <div class="pull-right">
    <%= will_paginate @events, next_label: '<i class="icon-arrow-right"></i>', previous_label: '<i class="icon-arrow-left" ></i>' %>
  </div>
</div>

app/views/chronicles/edit.html.erb
<h1>Editing chronicle</h1>

<%= render 'form' %>

<%= link_to 'Show', chronicle_path(@chronicle) %> |
<%= link_to 'Back', chronicles_path %>

app/views/chronicles/index.js.erb
$("#viewer-chronicles-index").html("<%= j render("index") %>");

app/views/chronicles/new.html.erb
<div class="last-minute">
  <h2>New chronicle</h2>
  <br/>

  <%= render 'form' %>

</div>

app/views/chronicles/show.html.erb
<div class="row">
  <div class="span12 crud-drawer">
    <div class="row">
      <div class="span6">
        <div class="crud-wrapper">
          <div class="crud-wrapper-inner">
            <div class="crud-panel">
              <div class="title wallpaper">
                <h3><%= @chronicle.name %></h3>

                <div class="dates"><%= get_chronicle_date(@chronicle) %></div>
              </div>

              <div class="details">

                <p> Description: <%= @chronicle.description %> </p>

                <p> Subject: <%= @chronicle.subject %> </p>

                <ul id="chronicle-tabs" class="nav nav-tabs">
                  <li class="active"><a href="#events-index-pane" data-toggle="tab">Events</a></li>
                  <li><a href="#areas-index-pane" data-toggle="tab">Areas</a></li>
                </ul>

              </div>

              <div class="tab-content">
                <div id="events-index-pane" class="tab-pane active">
                  <%= render 'events/index_by_chronicle' %>
                </div>
                <div id="areas-index-pane" class="tab-pane">
                  <%#= render 'areas/index_by_chronicle' %>
                </div>
              </div>

            </div>

            <div class="footer wallpaper"></div>
          </div>
        </div>
      </div>

      <div id="featured-event" class="span6">

        <!--<div id="empty-pane" class="tab-pane active">-->
          <!--<%#= render 'areas/index_by_chronicle' %>-->
        <!--</div>-->
        <!--<div id="new-event-pane" class="tab-pane">-->
          <!--<%#= render 'events/new' %>-->
        <!--</div>-->
        <!--<div id="edit-event-pane" class="tab-pane">-->
          <!--<%#= render 'areas/index_by_chronicle' %>-->
        <!--</div>-->
        <!--<div id="view-event-pane" class="tab-pane">-->
          <!--<%#= render 'areas/index_by_chronicle' %>-->
        <!--</div>-->
        <!--<div id="import-events-pane" class="tab-pane">-->
          <!--<%#= render 'areas/index_by_chronicle' %>-->
        <!--</div>-->
      </div>
    </div>

  </div>

</div>

<br/>

<%#= link_to 'New Event', new_chronicle_event_path(@chronicle, Event.new) %>


<div class="hidden-event-import" style="display:none;">
  <h2>Import</h2>

  <%= form_tag import_chronicle_events_path(@chronicle), multipart: true do %>
     <%= file_field_tag :file %>
     <%= submit_tag "Import" , class: 'btn' %>
  <% end %>
</div>

app/views/chronicles/show.js.erb
$("#events-index-pane").html("<%= j render 'events/index_by_chronicle' %>");